### PR TITLE
Cycle check

### PR DESCRIPTION
**Pull request by nblei**
This adds type checking for cyclic dependencies:

image

These dependencies are checked for `type` aliases, `struct`s and `union`s.

This is done with `CreateTypeDag` handler in Pass2.  It runs in Pass2 because it requires the symbol table made in Pass1.

Follow on work will be to add further type checking on type sizes.  This will go into Pass3, as it requires the [TypeDag] generated in Pass2.

### CODE REVIEW

**Comment by nblei** [comment]
Now also checks for undefined types:

image

Also, the Type DAG now stores sufficient information to create precise `AnalyzerError`s when traversing the DAG, rather than while traversing the AST.

**Comment by dalance** [comment]
Looks good!

There are some commented-out functions.
Can I merge them as is?

**Comment by nblei** [comment]
I pushed a commit removing those commented out functions.

**Comment by dalance** [comment]
Thanks.
I'll merge this PR.

**Pull request merged**
